import {
  Armchair,
  Bike,
  Book,
  Briefcase,
  Bus,
  Car,
  CircleEllipsis,
  Coffee,
  Cookie,
  Cpu,
  Droplets,
  Dumbbell,
  FileText,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandHeart,
  House,
  Hotel,
  KeyRound,
  Lamp,
  Landmark,
  Luggage,
  Map,
  Milestone,
  Package,
  Palette,
  ParkingCircle,
  Pill,
  Plane,
  Plug,
  Receipt,
  Repeat,
  ShieldPlus,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Sparkles,
  Stethoscope,
  Ticket,
  TrainFront,
  Tv,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-static'

export const CATEGORY_ICON_SVG: Record<string, string> = {
  Expenses: Wallet,

  'Expenses:Food': Utensils,
  'Expenses:Food:Coffee': Coffee,
  'Expenses:Food:Groceries': ShoppingBasket,
  'Expenses:Food:Delivery': Bike,
  'Expenses:Food:Snacks': Cookie,
  'Expenses:Food:Restaurant': UtensilsCrossed,
  'Expenses:Food:Dining': UtensilsCrossed,

  'Expenses:Transport': Car,
  'Expenses:Transport:Fuel': Fuel,
  'Expenses:Transport:Transit': TrainFront,
  'Expenses:Transport:Rideshare': Car,
  'Expenses:Transport:Tolls': Milestone,
  'Expenses:Transport:Parking': ParkingCircle,

  'Expenses:Housing': House,
  'Expenses:Housing:Rent': KeyRound,
  'Expenses:Housing:Utilities': Plug,
  'Expenses:Housing:Utilities:Electricity': Zap,
  'Expenses:Housing:Utilities:Water': Droplets,
  'Expenses:Housing:Utilities:Gas': Flame,
  'Expenses:Housing:Utilities:Internet': Wifi,
  'Expenses:Housing:Maintenance': Wrench,
  'Expenses:Housing:Furniture': Armchair,

  'Expenses:Health': Stethoscope,
  'Expenses:Health:Pharmacy': Pill,
  'Expenses:Health:Insurance': ShieldPlus,
  'Expenses:Health:Fitness': Dumbbell,

  'Expenses:Shopping': ShoppingBag,
  'Expenses:Shopping:Clothing': Shirt,
  'Expenses:Shopping:Electronics': Cpu,
  'Expenses:Shopping:Home': Lamp,
  'Expenses:Shopping:Personal': Sparkles,
  'Expenses:Gadgets': Cpu,

  'Expenses:Entertainment': Ticket,
  'Expenses:Entertainment:Streaming': Tv,
  'Expenses:Entertainment:Books': Book,
  'Expenses:Entertainment:Games': Gamepad2,
  'Expenses:Entertainment:Hobbies': Palette,

  'Expenses:Travel': Luggage,
  'Expenses:Travel:Hotels': Hotel,
  'Expenses:Travel:Flights': Plane,
  'Expenses:Travel:Tours': Map,
  'Expenses:Travel:Local': Bus,
  'Expenses:Travel:Rideshare': Car,
  'Expenses:Travel:Museums': Palette,
  'Expenses:Travel:Visas': FileText,

  'Expenses:Personal': User,
  'Expenses:Personal:Education': GraduationCap,
  'Expenses:Personal:Gifts': Gift,
  'Expenses:Personal:Charity': HandHeart,
  'Expenses:Personal:Family': Users,

  'Expenses:Services': Briefcase,
  'Expenses:Services:Subscriptions': Repeat,
  'Expenses:Services:Banking': Landmark,
  'Expenses:Services:Shipping': Package,

  'Expenses:Void': Sparkles,
  'Expenses:Taxes': Receipt,
  'Expenses:Misc': CircleEllipsis,
}

export function toChipSvg(raw: string): string {
  return raw
    .replace('width="24"', 'width="14"')
    .replace('height="24"', 'height="14"')
    .replace('stroke-width="2"', 'stroke-width="1.75"')
}
